#!/usr/bin/env bash
# check existing
if [ "$#" -ne 4 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi
PATH_TO=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO" "$USERNAME@$IP:~/"